# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - deploy

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - script: |
      ls ./dist/wtc/
    displayName: 'List contents'

  - task: CopyFilesOverSSH@0
    displayName: 'Deploy to server'
    inputs:
      sshEndpoint: zegarek-ssh
      sourceFolder: './dist/wtc/'
      targetFolder: /var/www/zegarek/
      cleanTargetFolder: true
      failOnEmptySource: true

